version: '3.1'

services:

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: clamaud
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: demo
    ports:
      - 6603:3306
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
